spring:

  # https://documentation.red-gate.com/fd/parameters-184127474.html
  flyway:
    create-schemas: true
    default-schema: dev_michael
    enabled: true

  datasource:
    url: jdbc:postgresql://188.120.224.165:5432/nastya
    username: nastya_app
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: michael_dev
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.postgresql10dialect

#logging:
#  level:
#    root: debug
